name: build
run-name: CI build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - $default-branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk-version: [11, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'temurin'

      - name: Install Ant
        run: sudo apt-get install -y ant ant-optional

      - name: Fetch And Dependencies
        run: ant -f fetch.xml -Ddest=user

#      - name: Install Apache Ant
#        shell: bash
#        env:
#          ANT_VERSION: '1.10.13'
#        run: |
#          wget --no-cookies https://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz
#          wget --no-cookies https://archive.apache.org/dist/ant/binaries/apache-ant-${ANT_VERSION}-bin.tar.gz.sha512
#          echo "$(cat apache-ant-${ANT_VERSION}-bin.tar.gz.sha512) apache-ant-${ANT_VERSION}-bin.tar.gz" | sha512sum -c
#          tar -zvxf apache-ant-${ANT_VERSION}-bin.tar.gz -C /opt/
#          echo "Add symlink"
#          ln -s /opt/apache-ant-${ANT_VERSION} /opt/ant
#          echo "Cleanup"
#          rm -f apache-ant-${ANT_VERSION}-bin.tar.gz
#          rm -f apache-ant-${ANT_VERSION}-bin.tar.gz.sha512

      - name: Run Ant Build
        shell: bash
        run: |
          ant -version
          ant -diagnostics
          ant -noinput -logger org.apache.tools.ant.NoBannerLogger clean build check
