name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        jdk-version: [11, 17, 21]
    name: JDK ${{ matrix.jdk-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'temurin'

      - uses: actions/cache@v4
        id: ant-lib-cache
        name: Ant Library Cache
        with:
          path: "~/.ant/lib/"
          key: ant-lib-cache-v1-jdk-${{ matrix.jdk-version }}-${{ hashFiles('.github/scripts/init-ant.sh') }}

      - uses: actions/cache@v4
        id: ivy-lib-cache
        name: Ivy Dependency Cache
        with:
          path: |
            ~/.ivy2/cache/
            lib/
          key: ivy-lib-cache-v1-jdk-${{ matrix.jdk-version }}-${{ hashFiles('ivy.xml') }}

      - name: Initialize Ant
        if: steps.ant-lib-cache.outputs.cache-hit != 'true'
        run: ./.github/scripts/init-ant.sh

      - name: Run Ant Build
        run: |
          ant -version
          ant -noinput -logger org.apache.tools.ant.NoBannerLogger clean build

      - name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Test Results - JDK ${{ matrix.jdk-version }}
          path: build/reports/unittest

      - name: Archive Code Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: Code Coverage Report - JDK ${{ matrix.jdk-version }}
          path: build/reports/coverage
