name: build
run-name: CI build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - $default-branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk-version: [11, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk-version }}
          distribution: 'temurin'

      - uses: actions/cache@v3
        id: ant-lib-cache
        name: Ant Library Cache
        with:
          path: "~/.ant/lib/"
          key: ant-lib-cache-v1-jdk-${{ matrix.jdk-version }}-${{ hashFiles('.github/scripts/init-ant.sh') }}

      - uses: actions/cache@v3
        id: ivy-lib-cache
        name: Ivy Dependency Cache
        with:
          path: |
            lib/
            build/temp/resolutioncache/
          key: ivy-lib-cache-v1-jdk-${{ matrix.jdk-version }}-${{ hashFiles('ivy.xml') }}

      - name: Initialize Ant
        if: steps.ant-lib-cache.outputs.cache-hit != 'true'
        run: ./.github/scripts/init-ant.sh

      - name: Run Ant Build
        run: |
          ant -version
          ant -noinput -logger org.apache.tools.ant.NoBannerLogger clean build check

      - name: Archive Test Results
        uses: actions/upload-artifact@v3
        with:
          name: JUnit Test Results
          path: build/reports/unittest

      - name: Archive Code Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: Code Coverage Report
          path: build/reports/coverage
